name: Build Petclinic

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Petclinic with Maven
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: Show build artifact
        run: ls -lh target
