
name: CI Pipeline
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master 
  #     - develop
      
    

jobs:
  build:
    uses: ./.github/workflows/javabuild.yml
    secrets: inherit
  sonar:
     uses: ./.github/workflows/sonar.yml
     needs: build
     secrets: inherit  
