
name: CI-test Pipeline
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master 
  #     - develop
      
    

jobs:
  build:
    uses: ./.github/workflows/build-petclinic.yml
    secrets: inherit
  sonar:
     uses: ./.github/workflows/sonarCI.yml
     needs: build
     secrets: inherit  
