name: CI-test Pipeline

on:
  workflow_dispatch

jobs:

  build:
    uses: ./.github/workflows/build-petclinicci.yml
    secrets: inherit
  
  sonar:
    needs: build
    uses: ./.github/workflows/Sonarci.yml
    secrets: inherit  
    
  test:
    uses: ./.github/workflows/testci.yml
    needs: sonar
    secrets: inherit
   
  imagepush:
    uses: ./.github/workflows/imagepushci.yml
    needs: sonar
    secrets: inherit
    
