name: Docker Image Build and Push

on:
  workflow_call:

jobs:
  image_push:
    runs-on: self-hosted

    env:
      DOCKER_IMAGE: kashimo0054/petapp:${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: petclinic-jar
          path: target

      - name: Verify Artifact
        run: ls -lh target

      - name: Build Docker Image
        run: |
          sudo docker build -t ${{ env.DOCKER_IMAGE }} .
          sudo docker save ${{ env.DOCKER_IMAGE }} > docker_image.tar

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: sudo docker push ${{ env.DOCKER_IMAGE }}

      # 🔹 New steps to update GitOps repo
      - name: Clone GitOps repo
        run: |
          git clone https://x-access-token:${{ secrets.GITOPS_TOKEN }}@github.com/Kashimo0054/petclinic-k8s-gitops.git
          cd petclinic-k8s-gitops

          sed -i "s|image: .*|image: ${{ env.DOCKER_IMAGE }}|" petclinic-deployment.yaml

          git config --global user.name "kashimo0054"
          git config --global user.email "sumeettanpure2729@gmail.com"
          git add petclinic-deployment.yaml
          git commit -m "Update image to ${{ env.DOCKER_IMAGE }}"
          git push
