name: Snyk Security Scan

on:
  workflow_call:

jobs:
  snyk:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Temporary Fix - Generate Maven Wrapper
        run: |
          mvn -N wrapper:wrapper
          chmod +x mvnw

      - name: Run Snyk Test
        run: snyk test --file=pom.xml --org=kashimo0054 --severity-threshold=high 
        continue-on-error: true
